import type { Metadata } from "next";
import "./globals.css";
import { Bai_Jamjuree } from "next/font/google";
import Footer from "./(routes)/_components/Menu/Footer";
import Header from "./(routes)/_components/Menu/Header";

export const metadata: Metadata = {
  title: "Luthier.com",
  description: "Generated by create next app",
};

const baiJamjuree = Bai_Jamjuree({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={baiJamjuree.className}>
        <div className="min-h-screen">
          <Header />
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
